name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        release_id: ${{ steps.release.outputs.releaseID }}
    steps:
    - name: Checkout Repository and Submodules
      # See https://github.com/actions/checkout/releases
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: recursive
    - name: Set up JDK
      # See https://github.com/actions/setup-java/releases
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: 25
        distribution: temurin
    - name: Setup Gradle
      # See https://github.com/gradle/actions/releases
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive Artifacts
      # See https://github.com/actions/upload-artifact/releases
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      if: success()
      with:
        name: ParadisuPlugin
        path: build/libs/ParadisuPlugin.jar
        if-no-files-found: error
    - name: Create Release
      # See https://github.com/Kas-tle/base-release-action/releases
      uses: Kas-tle/base-release-action@b89ab10da9dfaa0b5fb0ca9e77679c7c7d1297f8
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' }}
      id: release
      with:
        files: |
          build/libs/ParadisuPlugin.jar
        appID: ${{ secrets.RELEASE_APP_ID }}
        appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
        preRelease: ${{ github.ref_name != 'master' }}
        discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Setup NodeJS
      # See https://github.com/actions/setup-node/releases
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' && github.ref_name == 'master' }}
    - name: Publish Plugin to Servers
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' && github.ref_name == 'master' }}
      env:
        PTEROPUB_CONFIG: ${{ secrets.PTEROPUB_CONFIG }}
      run: npx pteropub
  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload Logs
      # See https://github.com/Kas-tle/release-build-log-action/releases
      if: ${{ success() && github.repository == 'Paradisu/ParadisuPlugin' }}
      uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.build.outputs.release_id }}